# Generated by Django 4.2 on 2024-06-30 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets', '0001_initial'),
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.comment'),
        ),
    ]
